@startuml
actor Website
interface SLOW
component [Slow\nService] as SL
interface AUTH
component [Authentication\nService] as AuthS

package "To be" {
component [Collector\nService] as CS
component [Queue] as queue
component [Query Service] as QueryServ
component [Store\nService] as SS
component [API Gateway\n(Cache,\nRate Limiter)] as GW
database Elasticsearch as DB
}
interface REST as RestCollector
interface REST as RestQuery


Website -right-> RestCollector
RestCollector -right- CS
CS .right.> AUTH : validate clientID
AUTH - AuthS
CS -down-> queue
queue -down-> SS
SS -down-> GW
GW .right.> SLOW
SLOW - SL
SS -right-> DB
DB <-right- QueryServ
QueryServ ..> AUTH : validate Auth-Token
QueryServ -right- RestQuery



@enduml